#!/bin/bash

PROMPT=$(hotdiva2000 -r 100 | sed 's/^\|$/"/g' | paste -sd,)

cat > index.html << EOF

<!DOCTYPE html>

<!--
made with love by kat @ girlonthemoon.xyz
-->

<html>
  <head>
    <title>hot diva 2004</title>
    <link rel="stylesheet" href="main.css">
  </head>
  <body>
  <section id="style">
	<header>
	    <h1>hot diva 2004</h1>
	</header>
	
	    <p>this is a prompt generator site, built with a single bash script, but with a catch: the prompt list is generated by <a href="https://github.com/charmbracelet/hotdiva2000">hotdiva2000</a>!</p>
    	<p>100 strings are generated every hour. so don't wait, click the below button to get some bizarre strings and use them as writing prompts!</p>

    <button onclick="makePrompts()">click me :)</button>
    <p id="prompts"></p>
    <script>
	    const prompts = [${PROMPT}];

	    function makePrompts() {
	      const random = Math.floor(Math.random() * prompts.length);
	      document.getElementById("prompts").innerText = prompts[random];
	    }
    </script>
  </section>

  <section id="credit">
  	<div class="credit-par">
	  <p><a href="https://tangled.org/katproto.girlonthemoon.xyz/hotdiva2004">source code</a></p>
	  <p><a href="https://girlonthemoon.xyz/elsewhere">find me elsewhere</a></p>
	  <p><a href="https://prompts.4-walls.net/">more prompt generators</a></p>
	</div>
  </section>
  </body>
</html>

EOF
